export default function Head() {
    return (
        <>
            <title>CMGT Showcase app</title>
            <meta content="width=device-width, initial-scale=1" name="viewport"/>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/images/favicons/favicon.ico"/>
            <meta charSet="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            <meta name="csrf-token" content="{{ csrf_token() }}"/>
            <meta name="og:site_name" content="CMGT Showcase | Hogeschool Rotterdam"/>
            <link rel="apple-touch-icon" sizes="120x120" href="/images/favicons/apple-touch-icon.png"/>
            <link rel="icon" type="image/png" sizes="32x32" href="/images/favicons/favicon-32x32.png"/>
            <link rel="icon" type="image/png" sizes="16x16" href="/images/favicons/favicon-16x16.png"/>
            <link rel="manifest" href="/manifest.webmanifest"/>
            <link rel="mask-icon" href="/images/favicons/safari-pinned-tab.svg" color="#5bbad5"/>
            <link rel="canonical" href=""/>
            <meta name="msapplication-TileColor" content="#da532c"/>
            <meta name="theme-color" content="#ffffff"/>
            <meta name="description" content=""/>
            <meta property="og:url" content=""/>
            <meta property="og:title" content=""/>
            <meta property="og:description" content=""/>
            <meta property="og:image" content=""/>
            <meta property="og:type" content="website"/>
        </>
    )
}
